services:
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    image: ghcr.io/y-l-g/lcs-gestion-congelateurs:main
    volumes:
      - congel_app_data:/data
      - congel_app_config:/config
      - congel_storage:/app/storage
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: sh -c 'php artisan octane:frankenphp --host=0.0.0.0'
    environment:
      - APP_NAME=congel
    secrets:
      - congel_DB_PASSWORD
      - congel_REDIS_PASSWORD
      - congel_APP_URL
      - congel_APP_KEY
      - congel_APP_DOMAIN
    entrypoint: start-container
    networks:
      - congel
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  congel_app_data:
  congel_app_config:
  ########################
  congel_storage:
  ##################################################
secrets:
  congel_DB_DATABASE:
    external: true
  congel_DB_PASSWORD:
    external: true
  congel_DB_USERNAME:
    external: true
  congel_REDIS_PASSWORD:
    external: true
  congel_APP_URL:
    external: true
  congel_APP_KEY:
    external: true
  congel_APP_DOMAIN:
    external: true
networks:
  congel:
    external: true
